apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mls-model
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mls-model
    spec:
      containers:
      - name: mls-model
        image: deployreg.azurecr.io/mls-model
        ports:
        - containerPort: 12800
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: deployreg.azurecr.io
---
apiVersion: v1
kind: Service
metadata:
  name: mls-model-svc
spec:
  selector:
    app: mls-model
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 12800
